# Generated by Django 5.2.4 on 2026-01-16 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ConfiguracaoEmpresa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(max_length=200, verbose_name="Nome da Empresa"),
                ),
                (
                    "cnpj",
                    models.CharField(blank=True, max_length=18, verbose_name="CNPJ"),
                ),
                ("endereco", models.TextField(blank=True, verbose_name="Endereço")),
                (
                    "telefone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Telefone"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="E-mail"
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="empresa/", verbose_name="Logo"
                    ),
                ),
                (
                    "observacoes_padrao",
                    models.TextField(
                        blank=True, verbose_name="Observações Padrão para Orçamentos"
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuração da Empresa",
                "verbose_name_plural": "Configurações da Empresa",
            },
        ),
    ]
