# Generated by Django 5.2.4 on 2026-01-16 13:26

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0001_initial"),
        ("financeiro", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="despesa",
            name="funcionario",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pagamentos",
                to="cadastros.funcionario",
                verbose_name="Funcionário",
            ),
        ),
        migrations.AddField(
            model_name="venda",
            name="numero_parcelas",
            field=models.PositiveIntegerField(
                default=1, verbose_name="Número de Parcelas"
            ),
        ),
        migrations.AddField(
            model_name="venda",
            name="tipo_pagamento",
            field=models.CharField(
                choices=[("a_vista", "À Vista"), ("parcelado", "Parcelado")],
                default="a_vista",
                max_length=15,
                verbose_name="Tipo de Pagamento",
            ),
        ),
        migrations.AlterField(
            model_name="despesa",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("fixa", "Fixa"),
                    ("variavel", "Variável"),
                    ("salario", "Salário"),
                ],
                default="variavel",
                max_length=10,
                verbose_name="Tipo",
            ),
        ),
        migrations.AlterField(
            model_name="venda",
            name="forma_pagamento",
            field=models.CharField(
                blank=True,
                choices=[
                    ("dinheiro", "Dinheiro"),
                    ("pix", "PIX"),
                    ("cartao_debito", "Cartão de Débito"),
                    ("cartao_credito", "Cartão de Crédito"),
                    ("boleto", "Boleto"),
                    ("transferencia", "Transferência"),
                    ("cheque", "Cheque"),
                ],
                max_length=20,
                verbose_name="Forma de Pagamento",
            ),
        ),
        migrations.CreateModel(
            name="FolhaPagamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mes", models.PositiveIntegerField(verbose_name="Mês")),
                ("ano", models.PositiveIntegerField(verbose_name="Ano")),
                (
                    "data_geracao",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Geração"
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=12, verbose_name="Total"
                    ),
                ),
                (
                    "processada",
                    models.BooleanField(default=False, verbose_name="Processada"),
                ),
            ],
            options={
                "verbose_name": "Folha de Pagamento",
                "verbose_name_plural": "Folhas de Pagamento",
                "ordering": ["-ano", "-mes"],
                "unique_together": {("mes", "ano")},
            },
        ),
        migrations.CreateModel(
            name="Parcela",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero",
                    models.PositiveIntegerField(verbose_name="Número da Parcela"),
                ),
                (
                    "valor",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="Valor",
                    ),
                ),
                (
                    "data_vencimento",
                    models.DateField(verbose_name="Data de Vencimento"),
                ),
                (
                    "data_pagamento",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de Pagamento"
                    ),
                ),
                ("pago", models.BooleanField(default=False, verbose_name="Pago")),
                (
                    "observacoes",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Observações"
                    ),
                ),
                (
                    "venda",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parcelas",
                        to="financeiro.venda",
                        verbose_name="Venda",
                    ),
                ),
            ],
            options={
                "verbose_name": "Parcela",
                "verbose_name_plural": "Parcelas",
                "ordering": ["venda", "numero"],
                "unique_together": {("venda", "numero")},
            },
        ),
    ]
