# Generated by Django 5.2.4 on 2026-01-16 13:04

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[("servico", "Serviço"), ("produto", "Produto")],
                        max_length=10,
                        verbose_name="Tipo",
                    ),
                ),
                ("nome", models.CharField(max_length=200, verbose_name="Nome")),
                (
                    "preco",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="Preço",
                    ),
                ),
                ("descricao", models.TextField(blank=True, verbose_name="Descrição")),
                (
                    "quantidade_estoque",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Obrigatório apenas para produtos",
                        verbose_name="Quantidade em Estoque",
                    ),
                ),
                (
                    "estoque_minimo",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Quantidade mínima para alerta",
                        verbose_name="Estoque Mínimo",
                    ),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
            ],
            options={
                "verbose_name": "Item",
                "verbose_name_plural": "Itens",
                "ordering": ["tipo", "nome"],
            },
        ),
    ]
